name: plux
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  dio: ^5.9.0
  json_annotation: ^4.9.0
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  flutter_dotenv: ^6.0.0
  riverpod_annotation: ^3.0.3
  hooks_riverpod: ^3.0.3
  skeletonizer: ^2.1.0+1
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.3.3
  connectivity_plus: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  riverpod_generator: ^3.0.3


flutter_gen:
  output: lib/src/config/generated/


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/files/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env

